module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.[jt]s?(x)'],
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        tsconfig: {
          jsx: 'react-jsx',
        },
      },
    ],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^react-native$': '<rootDir>/lib/attachments/__mocks__/react-native.ts',
    '^@react-native-async-storage/async-storage$': '<rootDir>/lib/attachments/__mocks__/async-storage.ts',
    '^react-native-url-polyfill/auto$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^expo-image-manipulator$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^@powersync/op-sqlite$': '<rootDir>/lib/attachments/__mocks__/powersync-op-sqlite.ts',
    '^@op-engineering/op-sqlite(.*)$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^expo-file-system/legacy$': '<rootDir>/lib/attachments/__mocks__/expo-file-system-legacy.ts',
    '^expo-file-system$': '<rootDir>/lib/attachments/__mocks__/expo-file-system.ts',
    '^@powersync/react-native$': '<rootDir>/lib/attachments/__mocks__/powersync-react-native.ts',
    '^@powersync/react$': '<rootDir>/lib/attachments/__mocks__/powersync-react.ts',
    '^@sentry/react-native$': '<rootDir>/lib/attachments/__mocks__/sentry-react-native.ts',
    '^uuid$': '<rootDir>/lib/attachments/__mocks__/uuid.ts',
    '^test-renderer$': '<rootDir>/lib/attachments/__mocks__/test-renderer.ts',
    '^lucide-react-native$': '<rootDir>/lib/attachments/__mocks__/lucide-react-native.ts',
    '^expo-document-picker$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^expo-sharing$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^expo-status-bar$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^react-native-safe-area-context$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^react-native-gesture-handler$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^@react-navigation/native$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^react-native-reanimated$': '<rootDir>/lib/attachments/__mocks__/react-native-reanimated.ts',
    '^react-native-purchases$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^posthog-react-native$': '<rootDir>/lib/attachments/__mocks__/empty.ts',
    '^@react-native-community/netinfo$': '<rootDir>/lib/attachments/__mocks__/netinfo.ts',
  },
};
